server:
  port: 9000
#zuul:
#  routes: #配置路由规则
#    first:
#      path: /user-service/**
#      serviceId: user-service
#      url: http://127.0.0.1:8000

#简化配置   键值是服务id  名称为映射路径
zuul:
  routes: #配置路由规则
    user-consumer: /user-consumer/**
  ignored-services:  #不能直接访问的服务  限制  返回404
    - user-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka,http://127.0.0.1:10001/eureka